### ISSUE TITLE
Populate with two fields

### ISSUE THREAD

**Issue by galileoguzman** [neithere/django-autoslug#13]
Hi, I have a question, ¿May I populate AutpSlugField with more than one field? I mean, if I want to generate slug with this model:

`class Article(models.Model):`
`name = models.CharField()`
`created_at = models.DateField()`
`slug = AutoSlugField(populate_from=('title', 'created_at'))`

This will generate the next slug: 'article-name-2016-08-04'

**Comment by adrianoramos** [comment]
populate_from=lambda instance: "{0}-{1}".format(instance.title, instance.created_at.isocalendar())
