### ISSUE TITLE
How to force update / refresh the slug field?

### ISSUE THREAD

**Issue by Calzzetta** [neithere/django-autoslug#19]
Hi,

I did a model for blog posts and I want to update the slug until the "published" value is False. After that the post owner can update the title but the slug will stay the same. My initial idea was to put this logic inside the save method but I didn't found the "refresh" method from AutoSlugField. How can I solve this?

Regards,
Douglas

**Comment by ArtemBernatskyy** [comment]
@Calzzetta , manually set slug to None and save model, then it will be forced to refresh slug.

**Comment by ArtemBernatskyy** [comment]
You may use post_save or pre_save (for further look at the source code of autoslug about when exactly it is operating) but in general it is a bad idea to change slug !

**Comment by ArtemBernatskyy** [comment]
As far as i see it uses post_save so imho you need to use pre_save where you can set slug to None.

P.S. not tested actually, i will be interested in your results :)

**Comment by UncleVasya** [comment]
I was wondering about same thing after adding autoslug to existing database :)

Suggestion of @ArtemBernatskyy worked for me:

```
players = Player.objects.all()
players_len = len(players)

with transaction.atomic():
  for i, player in enumerate(players):
    print 'Updating slug %d/%d' % (i, players_len)
    player.slug = None
    player.save()
```

---------------

Another way would possibly be to use `always_update` option:
```
class Player(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = AutoSlugField(populate_from='name', always_update=True)
```
http://django-autoslug.readthedocs.io/en/latest/fields.html

**Comment by ArtemBernatskyy** [comment]
@UncleVasya  do not update in loop better use django update https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.update

**Comment by UncleVasya** [comment]
@ArtemBernatskyy update() will not work here because it doesn't call model's save() method.

And since AutoSlugField isn't nullable, update(slug-None) will fail with DB exception.

**Comment by Calzzetta** [comment]
Thank you guys!

I removed the 'auto_update' attribute and now I am overwriting the value of the slug every time that I want to update it.
